### ISSUE TITLE
improve testing precompilation

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#309]
This idea could potentially be improved: https://github.com/LCSB-BioCore/COBREXA.jl/pull/303

We could try to warmup/precompile the solvers inside the docker container

**Comment by exaexa** [comment]
https://julialang.github.io/PackageCompiler.jl/dev/sysimages/

**Comment by exaexa** [comment]
Status after much testing:
- solvers can't be precompiled because Julia can't precompile mixed-package (MOI + JuMP + solver) stuff now
- sysImages are a solution but not for testing (you spend more time creating the sysImage than precompiling in the test)
- the "careful precompilation on all workers" already helped a bit

It would make sense to do sysImages in containers, esp for HPC deployment, so I'm moving that idea to #68

**Comment by exaexa** [comment]
But you are technically never testing 2 same versions of COBREXA, so the precompiled material is not going to get re-used anyway right?

**Comment by exaexa** [comment]
not sure.

thinking about it, if we make a julia sysImage with precompiled JuMP + some solver(s), which is 90% of the compilation time anyway, we pretty much solve the problem. Does that sound OK?

**Comment by exaexa** [comment]
Tests today:
- without PackageCompiler the tests run in ~3:40
- with a prepared environment I was able to shrink it to ~2:30
Precompilation of actual cobrexa is still pretty slow though, making up around 40 seconds there, but we can't do much with that as the code is different at each test.

Making the PackageCompiler image takes around 4 minutes.

**Comment by exaexa** [comment]
not really feasible anymore; there's julia cache (works pretty well) and most of the functionality is getting moved off the package, which will make fixing this basically unnecessary. Closing.
