### ISSUE TITLE
fix import of yeast GEM models

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#600]
All the models [here](https://github.com/SysBioChalmers/yeast-GEM/tree/main/model) present difficulties for our importing machinery. We need to fix this because it is popular model organism... 

Basically, the fields are either not imported or throw errors, try metabolite charges on the mat model or metabolite compartments on the sbml one. We should make it such that each different version of their yeast model looks the same when we import it into cobrexa in whichever format.

**Comment by exaexa** [comment]
is there some kind of list of all compatibility problems for this? The last time I tried the SBML it was OK except it needed a manual clarification of the units in the SBML. I suppose MAT model is broken most?

**Comment by stelmo** [comment]
no list that I am aware of :/ It really seems like people use new syntax whenever they make a model :/

**Comment by exaexa** [comment]
just wondering, is the yeast GEM available from some stable location so we can just throw tests at it?

**Comment by stelmo** [comment]
Yep, I _think_ the stable location is here: https://github.com/SysBioChalmers/yeast-GEM/tree/main/model

**Comment by exaexa** [comment]
Status after #611:
- the requested metabolite stuff should be parseable
- metabolite compartments don't parse out of MATModel because they are smashed into string IDs (not in an interoperable way, needs user intervention to get that done right)
- GRRs in MAT `rules` are index-based, which is also not very interoperable. Not going to support that now.
